CREATE DATABASE IF NOT EXISTS API_Activitats_db;
USE API_Activitats_db;

CREATE TABLE IF NOT EXISTS users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nom VARCHAR(50) NOT NULL,
	cognoms VARCHAR(100) NOT NULL,
	dni VARCHAR(20) UNIQUE NOT NULL,
	edat INT NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS activitats (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nom VARCHAR(100) NOT NULL,
	descripcio VARCHAR(250) NOT NULL,
	capacitat_maxima INT NOT NULL
);

CREATE TABLE IF NOT EXISTS inscripcions (
	id INT AUTO_INCREMENT PRIMARY KEY,
	usuari_id INT NOT NULL,
	activitat_id INT NOT NULL,
	FOREIGN KEY (usuari_id) REFERENCES users(id),
	FOREIGN KEY (activitat_id) REFERENCES activitats(id)
);
